name: Nix checks

on:
  pull_request:
  push:
    branches:
      - master
      - main

jobs:
  tests:
    runs-on: ubuntu-latest
    outputs:
      matrix: ${{ steps.set-matrix.outputs.matrix }}
    steps:
      - uses: actions/checkout@v4
      - uses: cachix/install-nix-action@v23
      - id: set-matrix
        name: Run tests
        run: nix-instantiate --eval --expr 'import ./tests.nix { }' --strict --json | jq -e '. == []' > /dev/null
